import Foundation

public enum PatchValidationError: Equatable, Sendable {
    case versionMismatch(expected: Int, got: Int)
    case invalidIngredientId(UUID)
    case invalidIngredientGroupId(UUID)
    case invalidStepId(UUID)
    case stepDoneImmutable(UUID)
    case internalConflict(String)
    case recipeIdMismatch(expected: UUID, got: UUID)
    /// Kept for backward compatibility; not generated by current patch cases.
    case invalidSubStepId(UUID)
    /// Kept for backward compatibility; not generated by current patch cases.
    case parentStepDone(UUID)
    case hardAvoidViolation(ingredient: String)
    case invalidNoteSectionId(UUID)
    case invalidMiseEnPlaceEntryId(UUID)
    case invalidMiseEnPlaceComponentId(UUID)

    public var code: PatchValidationErrorCode {
        switch self {
        case .versionMismatch:         return .VERSION_MISMATCH
        case .recipeIdMismatch:        return .INTERNAL_CONFLICT
        case .invalidIngredientId:     return .INVALID_INGREDIENT_ID
        case .invalidIngredientGroupId: return .INVALID_INGREDIENT_GROUP_ID
        case .invalidStepId:           return .INVALID_STEP_ID
        case .stepDoneImmutable:       return .STEP_DONE_IMMUTABLE
        case .internalConflict:        return .INTERNAL_CONFLICT
        case .invalidSubStepId:        return .INVALID_SUBSTEP_ID
        case .parentStepDone:          return .PARENT_STEP_DONE
        case .hardAvoidViolation:      return .HARD_AVOID_VIOLATION
        case .invalidNoteSectionId:    return .INVALID_NOTE_SECTION_ID
        case .invalidMiseEnPlaceEntryId:     return .INVALID_MISE_EN_PLACE_ENTRY_ID
        case .invalidMiseEnPlaceComponentId: return .INVALID_MISE_EN_PLACE_COMPONENT_ID
        }
    }
}

public enum PatchValidationErrorCode: String, Sendable {
    case VERSION_MISMATCH
    case INVALID_INGREDIENT_ID
    case INVALID_INGREDIENT_GROUP_ID
    case INVALID_STEP_ID
    case STEP_DONE_IMMUTABLE
    case INTERNAL_CONFLICT
    case INVALID_SUBSTEP_ID
    case PARENT_STEP_DONE
    case HARD_AVOID_VIOLATION
    case INVALID_NOTE_SECTION_ID
    case INVALID_MISE_EN_PLACE_ENTRY_ID
    case INVALID_MISE_EN_PLACE_COMPONENT_ID
}

public enum PatchValidationResult: Equatable, Sendable {
    case valid
    case invalid([PatchValidationError])
}

public enum PatchValidator {
    private static func hardAvoidMatch(in text: String, hardAvoids: [String]) -> String? {
        let lower = text.lowercased()
        return hardAvoids.first { lower.contains($0.lowercased()) }
    }

    private static func findStep(id: UUID, in steps: [Step]) -> Step? {
        for step in steps {
            if step.id == id { return step }
            if let subs = step.subSteps, let found = findStep(id: id, in: subs) {
                return found
            }
        }
        return nil
    }

    private static func findMiseEntry(id: UUID, in recipe: Recipe) -> MiseEnPlaceEntry? {
        recipe.miseEnPlace?.first { $0.id == id }
    }

    /// Returns the entry that owns the component with `id`, or nil when no entry does.
    private static func findMiseComponentOwner(componentId: UUID, in recipe: Recipe) -> MiseEnPlaceEntry? {
        recipe.miseEnPlace?.first { entry in
            if case .group(_, let components) = entry.content {
                return components.contains { $0.id == componentId }
            }
            return false
        }
    }

    public static func validate(patchSet: PatchSet, recipe: Recipe, hardAvoids: [String] = []) -> PatchValidationResult {
        var errors: [PatchValidationError] = []

        if patchSet.baseRecipeVersion != recipe.version {
            errors.append(.versionMismatch(expected: recipe.version, got: patchSet.baseRecipeVersion))
        }

        var removedIngredientIds: Set<UUID> = []
        var removedGroupIds: Set<UUID> = []
        var removedStepIds: Set<UUID> = []
        var pendingGroupIds: Set<UUID> = []
        var pendingStepIds: Set<UUID> = []
        var removedMiseEntryIds: Set<UUID> = []
        var removedMiseComponentIds: Set<UUID> = []
        /// Mise en place entries created earlier in this same PatchSet, mapped to
        /// whether they are vessel groups (true) or solo instructions (false).
        var pendingMiseEntryIsGroup: [UUID: Bool] = [:]

        for patch in patchSet.patches {
            switch patch {
            case .setTitle:
                break

            case .addIngredient(let groupId, let afterId, let text):
                if let match = hardAvoidMatch(in: text, hardAvoids: hardAvoids) {
                    errors.append(.hardAvoidViolation(ingredient: match))
                }
                if let groupId = groupId {
                    let groupExists = recipe.ingredients.contains { $0.id == groupId }
                    let groupRemoved = removedGroupIds.contains(groupId)
                    let groupPending = pendingGroupIds.contains(groupId)
                    if (!groupExists && !groupPending) || groupRemoved {
                        errors.append(.invalidIngredientGroupId(groupId))
                    } else if !groupPending, let afterId = afterId {
                        let group = recipe.ingredients.first(where: { $0.id == groupId })!
                        let afterExists = group.items.contains { $0.id == afterId }
                        let alreadyRemoved = removedIngredientIds.contains(afterId)
                        if !afterExists || alreadyRemoved {
                            errors.append(.invalidIngredientId(afterId))
                        }
                    }
                }

            case .updateIngredient(let id, let text):
                if let match = hardAvoidMatch(in: text, hardAvoids: hardAvoids) {
                    errors.append(.hardAvoidViolation(ingredient: match))
                }
                let existsInAnyGroup = recipe.ingredients.contains { group in
                    !removedGroupIds.contains(group.id) && group.items.contains { $0.id == id }
                }
                let alreadyRemoved = removedIngredientIds.contains(id)
                if !existsInAnyGroup || alreadyRemoved {
                    errors.append(.invalidIngredientId(id))
                }

            case .removeIngredient(let id):
                let existsInAnyGroup = recipe.ingredients.contains { group in
                    !removedGroupIds.contains(group.id) && group.items.contains { $0.id == id }
                }
                let alreadyRemoved = removedIngredientIds.contains(id)
                if !existsInAnyGroup || alreadyRemoved {
                    errors.append(.invalidIngredientId(id))
                } else {
                    removedIngredientIds.insert(id)
                }

            case .addIngredientGroup(_, _, let preassignedId):
                pendingGroupIds.insert(preassignedId ?? UUID())

            case .updateIngredientGroup(let id, _):
                let groupExists = recipe.ingredients.contains { $0.id == id }
                let groupRemoved = removedGroupIds.contains(id)
                if !groupExists || groupRemoved {
                    errors.append(.invalidIngredientGroupId(id))
                }

            case .removeIngredientGroup(let id):
                let groupExists = recipe.ingredients.contains { $0.id == id }
                let groupRemoved = removedGroupIds.contains(id)
                if !groupExists || groupRemoved {
                    errors.append(.invalidIngredientGroupId(id))
                } else {
                    removedGroupIds.insert(id)
                    if let group = recipe.ingredients.first(where: { $0.id == id }) {
                        group.items.forEach { removedIngredientIds.insert($0.id) }
                    }
                }

            case .addStep(let parentId, let afterId, let text, let preassignedStepId):
                if let preassignedStepId {
                    pendingStepIds.insert(preassignedStepId)
                }
                if let match = hardAvoidMatch(in: text, hardAvoids: hardAvoids) {
                    errors.append(.hardAvoidViolation(ingredient: match))
                }
                if let parentId = parentId {
                    let parentRemoved = removedStepIds.contains(parentId)
                    let parentPending = pendingStepIds.contains(parentId)
                    if parentPending && !parentRemoved {
                        break
                    }
                    guard let parent = findStep(id: parentId, in: recipe.steps), !parentRemoved else {
                        errors.append(.invalidStepId(parentId))
                        break
                    }
                    if parent.effectiveStatus == .done {
                        errors.append(.stepDoneImmutable(parentId))
                    }
                    if let afterId = afterId {
                        let existsInParent = parent.subSteps?.contains { $0.id == afterId } ?? false
                        if !existsInParent {
                            errors.append(.invalidStepId(afterId))
                        }
                    }
                } else if let afterId = afterId {
                    let existsAtTopLevel = recipe.steps.contains { $0.id == afterId }
                    let alreadyRemoved = removedStepIds.contains(afterId)
                    if !existsAtTopLevel || alreadyRemoved {
                        errors.append(.invalidStepId(afterId))
                    }
                }

            case .updateStep(let id, let text):
                if let match = hardAvoidMatch(in: text, hardAvoids: hardAvoids) {
                    errors.append(.hardAvoidViolation(ingredient: match))
                }
                let alreadyRemoved = removedStepIds.contains(id)
                guard let step = findStep(id: id, in: recipe.steps), !alreadyRemoved else {
                    errors.append(.invalidStepId(id))
                    break
                }
                if step.effectiveStatus == .done {
                    errors.append(.stepDoneImmutable(id))
                }

            case .removeStep(let id):
                let alreadyRemoved = removedStepIds.contains(id)
                guard let step = findStep(id: id, in: recipe.steps), !alreadyRemoved else {
                    errors.append(.invalidStepId(id))
                    break
                }
                if step.effectiveStatus == .done {
                    errors.append(.stepDoneImmutable(id))
                    break
                }
                removedStepIds.insert(id)

            case .setStepNotes(let stepId, _):
                let alreadyRemoved = removedStepIds.contains(stepId)
                let isPending = pendingStepIds.contains(stepId)
                if isPending && !alreadyRemoved {
                    break
                }
                guard let step = findStep(id: stepId, in: recipe.steps), !alreadyRemoved else {
                    errors.append(.invalidStepId(stepId))
                    break
                }
                if step.effectiveStatus == .done {
                    errors.append(.stepDoneImmutable(stepId))
                }

            case .addMiseEnPlaceEntry(let afterId, let vesselName, let items, let preassignedId):
                for item in items {
                    if let match = hardAvoidMatch(in: item, hardAvoids: hardAvoids) {
                        errors.append(.hardAvoidViolation(ingredient: match))
                    }
                }
                if items.isEmpty {
                    errors.append(.internalConflict("add_mise_en_place_entry requires at least one item"))
                } else if vesselName == nil && items.count != 1 {
                    errors.append(.internalConflict("a solo mise en place entry must have exactly one item"))
                }
                if let preassignedId {
                    pendingMiseEntryIsGroup[preassignedId] = (vesselName != nil)
                }
                if let afterId {
                    let exists = findMiseEntry(id: afterId, in: recipe) != nil
                    let pending = pendingMiseEntryIsGroup[afterId] != nil
                    if (!exists && !pending) || removedMiseEntryIds.contains(afterId) {
                        errors.append(.invalidMiseEnPlaceEntryId(afterId))
                    }
                }

            case .updateMiseEnPlaceEntry(let id, let text):
                if let match = hardAvoidMatch(in: text, hardAvoids: hardAvoids) {
                    errors.append(.hardAvoidViolation(ingredient: match))
                }
                let exists = findMiseEntry(id: id, in: recipe) != nil
                let pending = pendingMiseEntryIsGroup[id] != nil
                if (!exists && !pending) || removedMiseEntryIds.contains(id) {
                    errors.append(.invalidMiseEnPlaceEntryId(id))
                }

            case .removeMiseEnPlaceEntry(let id):
                let existing = findMiseEntry(id: id, in: recipe)
                let pending = pendingMiseEntryIsGroup[id] != nil
                if (existing == nil && !pending) || removedMiseEntryIds.contains(id) {
                    errors.append(.invalidMiseEnPlaceEntryId(id))
                } else {
                    removedMiseEntryIds.insert(id)
                    pendingMiseEntryIsGroup.removeValue(forKey: id)
                    if let existing, case .group(_, let components) = existing.content {
                        components.forEach { removedMiseComponentIds.insert($0.id) }
                    }
                }

            case .addMiseEnPlaceComponent(let entryId, let afterId, let text):
                if let match = hardAvoidMatch(in: text, hardAvoids: hardAvoids) {
                    errors.append(.hardAvoidViolation(ingredient: match))
                }
                if let pendingIsGroup = pendingMiseEntryIsGroup[entryId] {
                    if !pendingIsGroup {
                        errors.append(.internalConflict("cannot add a component to a solo mise en place entry"))
                    }
                    break
                }
                guard let entry = findMiseEntry(id: entryId, in: recipe),
                      !removedMiseEntryIds.contains(entryId) else {
                    errors.append(.invalidMiseEnPlaceEntryId(entryId))
                    break
                }
                guard case .group(_, let components) = entry.content else {
                    errors.append(.internalConflict("cannot add a component to a solo mise en place entry"))
                    break
                }
                if let afterId {
                    let exists = components.contains { $0.id == afterId }
                    if !exists || removedMiseComponentIds.contains(afterId) {
                        errors.append(.invalidMiseEnPlaceComponentId(afterId))
                    }
                }

            case .updateMiseEnPlaceComponent(let id, let text):
                if let match = hardAvoidMatch(in: text, hardAvoids: hardAvoids) {
                    errors.append(.hardAvoidViolation(ingredient: match))
                }
                guard let owner = findMiseComponentOwner(componentId: id, in: recipe),
                      !removedMiseEntryIds.contains(owner.id),
                      !removedMiseComponentIds.contains(id) else {
                    errors.append(.invalidMiseEnPlaceComponentId(id))
                    break
                }

            case .removeMiseEnPlaceComponent(let id):
                guard let owner = findMiseComponentOwner(componentId: id, in: recipe),
                      !removedMiseEntryIds.contains(owner.id),
                      !removedMiseComponentIds.contains(id) else {
                    errors.append(.invalidMiseEnPlaceComponentId(id))
                    break
                }
                removedMiseComponentIds.insert(id)

            case .addNoteSection:
                break

            case .updateNoteSection(let id, _, _):
                let exists = recipe.notes?.contains { $0.id == id } ?? false
                if !exists {
                    errors.append(.invalidNoteSectionId(id))
                }

            case .removeNoteSection(let id):
                let exists = recipe.notes?.contains { $0.id == id } ?? false
                if !exists {
                    errors.append(.invalidNoteSectionId(id))
                }
            }
        }

        return errors.isEmpty ? .valid : .invalid(errors)
    }
}
