import Foundation

public enum PatchValidationError: Equatable, Sendable {
    case versionMismatch(expected: Int, got: Int)
    case invalidIngredientId(UUID)
    case invalidIngredientGroupId(UUID)
    case invalidStepId(UUID)
    case stepDoneImmutable(UUID)
    case internalConflict(String)
    case recipeIdMismatch(expected: UUID, got: UUID)
    /// Kept for backward compatibility; not generated by current patch cases.
    case invalidSubStepId(UUID)
    /// Kept for backward compatibility; not generated by current patch cases.
    case parentStepDone(UUID)
    case hardAvoidViolation(ingredient: String)
    case invalidNoteSectionId(UUID)

    public var code: PatchValidationErrorCode {
        switch self {
        case .versionMismatch:         return .VERSION_MISMATCH
        case .recipeIdMismatch:        return .INTERNAL_CONFLICT
        case .invalidIngredientId:     return .INVALID_INGREDIENT_ID
        case .invalidIngredientGroupId: return .INVALID_INGREDIENT_GROUP_ID
        case .invalidStepId:           return .INVALID_STEP_ID
        case .stepDoneImmutable:       return .STEP_DONE_IMMUTABLE
        case .internalConflict:        return .INTERNAL_CONFLICT
        case .invalidSubStepId:        return .INVALID_SUBSTEP_ID
        case .parentStepDone:          return .PARENT_STEP_DONE
        case .hardAvoidViolation:      return .HARD_AVOID_VIOLATION
        case .invalidNoteSectionId:    return .INVALID_NOTE_SECTION_ID
        }
    }
}

public enum PatchValidationErrorCode: String, Sendable {
    case VERSION_MISMATCH
    case INVALID_INGREDIENT_ID
    case INVALID_INGREDIENT_GROUP_ID
    case INVALID_STEP_ID
    case STEP_DONE_IMMUTABLE
    case INTERNAL_CONFLICT
    case INVALID_SUBSTEP_ID
    case PARENT_STEP_DONE
    case HARD_AVOID_VIOLATION
    case INVALID_NOTE_SECTION_ID
}

public enum PatchValidationResult: Equatable, Sendable {
    case valid
    case invalid([PatchValidationError])
}

public enum PatchValidator {
    private static func hardAvoidMatch(in text: String, hardAvoids: [String]) -> String? {
        let lower = text.lowercased()
        return hardAvoids.first { lower.contains($0.lowercased()) }
    }

    private static func findStep(id: UUID, in steps: [Step]) -> Step? {
        for step in steps {
            if step.id == id { return step }
            if let subs = step.subSteps, let found = findStep(id: id, in: subs) {
                return found
            }
        }
        return nil
    }

    public static func validate(patchSet: PatchSet, recipe: Recipe, hardAvoids: [String] = []) -> PatchValidationResult {
        var errors: [PatchValidationError] = []

        if patchSet.baseRecipeVersion != recipe.version {
            errors.append(.versionMismatch(expected: recipe.version, got: patchSet.baseRecipeVersion))
        }

        var removedIngredientIds: Set<UUID> = []
        var removedGroupIds: Set<UUID> = []
        var removedStepIds: Set<UUID> = []

        for patch in patchSet.patches {
            switch patch {
            case .setTitle:
                break

            case .addIngredient(let groupId, let afterId, let text):
                if let match = hardAvoidMatch(in: text, hardAvoids: hardAvoids) {
                    errors.append(.hardAvoidViolation(ingredient: match))
                }
                if let groupId = groupId {
                    let groupExists = recipe.ingredients.contains { $0.id == groupId }
                    let groupRemoved = removedGroupIds.contains(groupId)
                    if !groupExists || groupRemoved {
                        errors.append(.invalidIngredientGroupId(groupId))
                    } else if let afterId = afterId {
                        let group = recipe.ingredients.first(where: { $0.id == groupId })!
                        let afterExists = group.items.contains { $0.id == afterId }
                        let alreadyRemoved = removedIngredientIds.contains(afterId)
                        if !afterExists || alreadyRemoved {
                            errors.append(.invalidIngredientId(afterId))
                        }
                    }
                }

            case .updateIngredient(let id, let text):
                if let match = hardAvoidMatch(in: text, hardAvoids: hardAvoids) {
                    errors.append(.hardAvoidViolation(ingredient: match))
                }
                let existsInAnyGroup = recipe.ingredients.contains { group in
                    !removedGroupIds.contains(group.id) && group.items.contains { $0.id == id }
                }
                let alreadyRemoved = removedIngredientIds.contains(id)
                if !existsInAnyGroup || alreadyRemoved {
                    errors.append(.invalidIngredientId(id))
                }

            case .removeIngredient(let id):
                let existsInAnyGroup = recipe.ingredients.contains { group in
                    !removedGroupIds.contains(group.id) && group.items.contains { $0.id == id }
                }
                let alreadyRemoved = removedIngredientIds.contains(id)
                if !existsInAnyGroup || alreadyRemoved {
                    errors.append(.invalidIngredientId(id))
                } else {
                    removedIngredientIds.insert(id)
                }

            case .addIngredientGroup:
                break

            case .updateIngredientGroup(let id, _):
                let groupExists = recipe.ingredients.contains { $0.id == id }
                let groupRemoved = removedGroupIds.contains(id)
                if !groupExists || groupRemoved {
                    errors.append(.invalidIngredientGroupId(id))
                }

            case .removeIngredientGroup(let id):
                let groupExists = recipe.ingredients.contains { $0.id == id }
                let groupRemoved = removedGroupIds.contains(id)
                if !groupExists || groupRemoved {
                    errors.append(.invalidIngredientGroupId(id))
                } else {
                    removedGroupIds.insert(id)
                    if let group = recipe.ingredients.first(where: { $0.id == id }) {
                        group.items.forEach { removedIngredientIds.insert($0.id) }
                    }
                }

            case .addStep(let parentId, let afterId, let text, _):
                if let match = hardAvoidMatch(in: text, hardAvoids: hardAvoids) {
                    errors.append(.hardAvoidViolation(ingredient: match))
                }
                if let parentId = parentId {
                    let parentRemoved = removedStepIds.contains(parentId)
                    guard let parent = findStep(id: parentId, in: recipe.steps), !parentRemoved else {
                        errors.append(.invalidStepId(parentId))
                        break
                    }
                    if parent.effectiveStatus == .done {
                        errors.append(.stepDoneImmutable(parentId))
                    }
                    if let afterId = afterId {
                        let existsInParent = parent.subSteps?.contains { $0.id == afterId } ?? false
                        if !existsInParent {
                            errors.append(.invalidStepId(afterId))
                        }
                    }
                } else if let afterId = afterId {
                    let existsAtTopLevel = recipe.steps.contains { $0.id == afterId }
                    let alreadyRemoved = removedStepIds.contains(afterId)
                    if !existsAtTopLevel || alreadyRemoved {
                        errors.append(.invalidStepId(afterId))
                    }
                }

            case .updateStep(let id, let text):
                if let match = hardAvoidMatch(in: text, hardAvoids: hardAvoids) {
                    errors.append(.hardAvoidViolation(ingredient: match))
                }
                let alreadyRemoved = removedStepIds.contains(id)
                guard let step = findStep(id: id, in: recipe.steps), !alreadyRemoved else {
                    errors.append(.invalidStepId(id))
                    break
                }
                if step.effectiveStatus == .done {
                    errors.append(.stepDoneImmutable(id))
                }

            case .removeStep(let id):
                let alreadyRemoved = removedStepIds.contains(id)
                guard let step = findStep(id: id, in: recipe.steps), !alreadyRemoved else {
                    errors.append(.invalidStepId(id))
                    break
                }
                if step.effectiveStatus == .done {
                    errors.append(.stepDoneImmutable(id))
                    break
                }
                removedStepIds.insert(id)

            case .setStepNotes(let stepId, _):
                let alreadyRemoved = removedStepIds.contains(stepId)
                guard let step = findStep(id: stepId, in: recipe.steps), !alreadyRemoved else {
                    errors.append(.invalidStepId(stepId))
                    break
                }
                if step.effectiveStatus == .done {
                    errors.append(.stepDoneImmutable(stepId))
                }

            case .addNoteSection:
                break

            case .updateNoteSection(let id, _, _):
                let exists = recipe.notes?.contains { $0.id == id } ?? false
                if !exists {
                    errors.append(.invalidNoteSectionId(id))
                }

            case .removeNoteSection(let id):
                let exists = recipe.notes?.contains { $0.id == id } ?? false
                if !exists {
                    errors.append(.invalidNoteSectionId(id))
                }
            }
        }

        return errors.isEmpty ? .valid : .invalid(errors)
    }
}
